from core.workbook import Workbook
workbook=Workbook()
sheet1=workbook.add_sheet("Sheet1")
sheet2=workbook.add_sheet("Sheet2")
sheet1.set_cell("A1","Hello")
sheet1.set_cell("B1",123)
sheet2.set_cell("A1","Second Sheet")
print("Sheet 1:",sheet1.name)
print("Sheet 1 A1:",sheet1.get_cell("A1").value)
print("Sheet 1 B1:",sheet1.get_cell("B1").value)
print("Sheet 2:",sheet2.name)
print("Sheet 2 A1:",sheet2.get_cell("A1").value)
print("Sheet 1 missing cell:",sheet1.get_cell("Z99"))
print("Sheet 2 missing cell:",sheet2.get_cell("Z99"))
print("Workbook sheets:",[sheet.name for sheet in workbook.sheets])