from PyQt6.QtCore import Qt
from PyQt6.QtGui import QAction
from PyQt6.QtWidgets import QToolBar

class ToolbarPlugin:
    def __init__(self,spreadsheet):
        self.spreadsheet=spreadsheet
        self.toolbar=QToolBar("Toolbar")
        self.toolbar.setMovable(False)
        self.toolbar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        spreadsheet.addToolBar(self.toolbar)
        self.new_action=QAction("New",spreadsheet)
        self.open_action=QAction("Open",spreadsheet)
        self.save_action=QAction("Save",spreadsheet)
        self.export_pdf_action=QAction("Export PDF",spreadsheet)
        self.undo_action=QAction("Undo",spreadsheet)
        self.redo_action=QAction("Redo",spreadsheet)
        self.copy_action=QAction("Copy",spreadsheet)
        self.cut_action=QAction("Cut",spreadsheet)
        self.paste_action=QAction("Paste",spreadsheet)
        self.bold_action=QAction("Bold",spreadsheet)
        self.bold_action.setCheckable(True)
        self.italic_action=QAction("Italic",spreadsheet)
        self.italic_action.setCheckable(True)
        self.underline_action=QAction("Underline",spreadsheet)
        self.underline_action.setCheckable(True)
        self.left_action=QAction("Left",spreadsheet)
        self.center_action=QAction("Center",spreadsheet)
        self.right_action=QAction("Right",spreadsheet)
        self.top_action=QAction("Top",spreadsheet)
        self.middle_action=QAction("Middle",spreadsheet)
        self.bottom_action=QAction("Bottom",spreadsheet)
        self.font_color_action=QAction("Font Color",spreadsheet)
        self.fill_color_action=QAction("Fill Color",spreadsheet)
        self.image_action=QAction("Image",spreadsheet)
        self.pdf_action=QAction("PDF",spreadsheet)
        self.date_action=QAction("Date",spreadsheet)
        self.toolbar.addAction(self.new_action)
        self.toolbar.addAction(self.open_action)
        self.toolbar.addAction(self.save_action)
        self.toolbar.addAction(self.export_pdf_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.undo_action)
        self.toolbar.addAction(self.redo_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.copy_action)
        self.toolbar.addAction(self.cut_action)
        self.toolbar.addAction(self.paste_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.bold_action)
        self.toolbar.addAction(self.italic_action)
        self.toolbar.addAction(self.underline_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.left_action)
        self.toolbar.addAction(self.center_action)
        self.toolbar.addAction(self.right_action)
        self.toolbar.addAction(self.top_action)
        self.toolbar.addAction(self.middle_action)
        self.toolbar.addAction(self.bottom_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.font_color_action)
        self.toolbar.addAction(self.fill_color_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.image_action)
        self.toolbar.addAction(self.pdf_action)
        self.toolbar.addAction(self.date_action)