from PyQt6.QtGui import QAction

class MenuPlugin:
    def __init__(self,spreadsheet):
        self.spreadsheet=spreadsheet
        menubar=spreadsheet.menuBar()
        file_menu=menubar.addMenu("File")
        edit_menu=menubar.addMenu("Edit")
        format_menu=menubar.addMenu("Format")
        insert_menu=menubar.addMenu("Insert")
        align_menu=menubar.addMenu("Alignment")
        self.new_action=QAction("New",spreadsheet)
        self.new_tab_action=QAction("New Tab",spreadsheet)
        self.save_all_action=QAction("Save All Tabs",spreadsheet)
        self.open_action=QAction("Open",spreadsheet)
        self.save_action=QAction("Save",spreadsheet)
        self.export_pdf_action=QAction("Export PDF",spreadsheet)
        self.undo_action=QAction("Undo",spreadsheet)
        self.redo_action=QAction("Redo",spreadsheet)
        self.copy_action=QAction("Copy",spreadsheet)
        self.cut_action=QAction("Cut",spreadsheet)
        self.paste_action=QAction("Paste",spreadsheet)
        self.bold_action=QAction("Bold",spreadsheet)
        self.bold_action.setCheckable(True)
        self.italic_action=QAction("Italic",spreadsheet)
        self.italic_action.setCheckable(True)
        self.underline_action=QAction("Underline",spreadsheet)
        self.underline_action.setCheckable(True)
        self.left_action=QAction("Left",spreadsheet)
        self.center_action=QAction("Center",spreadsheet)
        self.right_action=QAction("Right",spreadsheet)
        self.top_action=QAction("Top",spreadsheet)
        self.middle_action=QAction("Middle",spreadsheet)
        self.bottom_action=QAction("Bottom",spreadsheet)
        self.font_color_action=QAction("Font Color",spreadsheet)
        self.fill_color_action=QAction("Fill Color",spreadsheet)
        self.insert_image_action=QAction("Image",spreadsheet)
        self.insert_pdf_action=QAction("PDF",spreadsheet)
        self.insert_date_action=QAction("Date",spreadsheet)
        file_menu.addAction(self.new_action)
        file_menu.addAction(self.new_tab_action)
        file_menu.addAction(self.save_all_action)
        file_menu.addAction(self.open_action)
        file_menu.addAction(self.save_action)
        file_menu.addSeparator()
        file_menu.addAction(self.export_pdf_action)
        edit_menu.addAction(self.undo_action)
        edit_menu.addAction(self.redo_action)
        edit_menu.addSeparator()
        edit_menu.addAction(self.copy_action)
        edit_menu.addAction(self.cut_action)
        edit_menu.addAction(self.paste_action)
        format_menu.addAction(self.bold_action)
        format_menu.addAction(self.italic_action)
        format_menu.addAction(self.underline_action)
        format_menu.addSeparator()
        format_menu.addAction(self.font_color_action)
        format_menu.addAction(self.fill_color_action)
        align_menu.addAction(self.left_action)
        align_menu.addAction(self.center_action)
        align_menu.addAction(self.right_action)
        align_menu.addSeparator()
        align_menu.addAction(self.top_action)
        align_menu.addAction(self.middle_action)
        align_menu.addAction(self.bottom_action)
        insert_menu.addAction(self.insert_image_action)
        insert_menu.addAction(self.insert_pdf_action)
        insert_menu.addAction(self.insert_date_action)