from PyQt6.QtCore import Qt
from PyQt6.QtGui import QAction
from PyQt6.QtWidgets import QToolBar, QStyle, QComboBox

class ToolbarPlugin:
    def __init__(self,spreadsheet):
        self.spreadsheet=spreadsheet
        self.toolbar=QToolBar("Toolbar")
        self.toolbar.setMovable(False)
        self.toolbar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        spreadsheet.addToolBar(self.toolbar)
        style=spreadsheet.style()
        self.new_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_FileIcon),"",spreadsheet)
        self.new_action.setToolTip("New File")
        self.new_action.setStatusTip("New File")
        self.open_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_DialogOpenButton),"",spreadsheet)
        self.open_action.setToolTip("Open File")
        self.open_action.setStatusTip("Open File")
        self.save_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_DialogSaveButton),"",spreadsheet)
        self.save_action.setToolTip("Save File")
        self.save_action.setStatusTip("Save File")
        self.export_pdf_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_DriveFDIcon),"",spreadsheet)
        self.export_pdf_action.setToolTip("Export PDF")
        self.export_pdf_action.setStatusTip("Export PDF")
        self.export_image_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_ComputerIcon),"",spreadsheet)
        self.export_image_action.setToolTip("Export Image")
        self.export_image_action.setStatusTip("Export Image")
        self.undo_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_ArrowBack),"",spreadsheet)
        self.undo_action.setToolTip("Undo")
        self.undo_action.setStatusTip("Undo")
        self.redo_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_ArrowForward),"",spreadsheet)
        self.redo_action.setToolTip("Redo")
        self.redo_action.setStatusTip("Redo")
        self.copy_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_FileDialogDetailedView),"",spreadsheet)
        self.copy_action.setToolTip("Copy")
        self.copy_action.setStatusTip("Copy")
        self.cut_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_TrashIcon),"",spreadsheet)
        self.cut_action.setToolTip("Cut")
        self.cut_action.setStatusTip("Cut")
        self.paste_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_FileDialogListView),"",spreadsheet)
        self.paste_action.setToolTip("Paste")
        self.paste_action.setStatusTip("Paste")
        self.bold_action=QAction("B",spreadsheet)
        self.bold_action.setCheckable(True)
        self.bold_action.setToolTip("Bold")
        self.bold_action.setStatusTip("Bold")
        self.italic_action=QAction("I",spreadsheet)
        self.italic_action.setCheckable(True)
        self.italic_action.setToolTip("Italic")
        self.italic_action.setStatusTip("Italic")
        self.underline_action=QAction("U",spreadsheet)
        self.underline_action.setCheckable(True)
        self.underline_action.setToolTip("Underline")
        self.underline_action.setStatusTip("Underline")
        self.strike_action=QAction("S",spreadsheet)
        self.strike_action.setCheckable(True)
        self.strike_action.setToolTip("Strikethrough")
        self.strike_action.setStatusTip("Strikethrough")
        self.wrap_action=QAction("↵",spreadsheet)
        self.wrap_action.setCheckable(True)
        self.wrap_action.setToolTip("Wrap Text")
        self.wrap_action.setStatusTip("Wrap Text")
        self.merge_action=QAction("Merge / Unmerge",spreadsheet)
        self.merge_action.setToolTip("Merge / Unmerge Cells")
        self.merge_action.setStatusTip("Merge / Unmerge Cells")
        self.horizontal_alignment=QComboBox()
        self.horizontal_alignment.addItems(["Left","Center","Right"])
        self.horizontal_alignment.setToolTip("Horizontal Alignment")
        self.vertical_alignment=QComboBox()
        self.vertical_alignment.addItems(["Top","Middle","Bottom"])
        self.vertical_alignment.setToolTip("Vertical Alignment")
        self.font_color_action=QAction("A",spreadsheet)
        self.font_color_action.setToolTip("Font Color")
        self.font_color_action.setStatusTip("Font Color")
        self.fill_color_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_DialogApplyButton),"",spreadsheet)
        self.fill_color_action.setToolTip("Fill Color")
        self.fill_color_action.setStatusTip("Fill Color")
        self.image_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_FileDialogContentsView),"",spreadsheet)
        self.image_action.setToolTip("Insert Image")
        self.image_action.setStatusTip("Insert Image")
        self.pdf_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_FileIcon),"",spreadsheet)
        self.pdf_action.setToolTip("Insert PDF")
        self.pdf_action.setStatusTip("Insert PDF")
        self.date_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_BrowserReload),"",spreadsheet)
        self.date_action.setToolTip("Insert Date")
        self.date_action.setStatusTip("Insert Date")
        self.toolbar.addAction(self.new_action)
        self.toolbar.addAction(self.open_action)
        self.toolbar.addAction(self.save_action)
        self.toolbar.addAction(self.export_pdf_action)
        self.toolbar.addAction(self.export_image_action)
        self.toolbar.addAction(self.export_image_action)
        self.export_image_action=QAction(style.standardIcon(QStyle.StandardPixmap.SP_ComputerIcon),"",spreadsheet)
        self.export_image_action.setToolTip("Export Image")
        self.export_image_action.setStatusTip("Export Image")
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.undo_action)
        self.toolbar.addAction(self.redo_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.copy_action)
        self.toolbar.addAction(self.cut_action)
        self.toolbar.addAction(self.paste_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.bold_action)
        self.toolbar.addAction(self.italic_action)
        self.toolbar.addAction(self.underline_action)
        self.toolbar.addAction(self.strike_action)
        self.toolbar.addAction(self.wrap_action)
        self.toolbar.addAction(self.merge_action)
        self.toolbar.addSeparator()
        self.toolbar.addWidget(self.horizontal_alignment)
        self.toolbar.addWidget(self.vertical_alignment)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.font_color_action)
        self.toolbar.addAction(self.fill_color_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.image_action)
        self.toolbar.addAction(self.pdf_action)
        self.toolbar.addAction(self.date_action)