import os
from PyQt6.QtCore import Qt, QSize
from PyQt6.QtGui import QAction, QIcon
from PyQt6.QtWidgets import QToolBar, QComboBox, QToolButton, QMenu

class ToolbarPlugin:
    def __init__(self,spreadsheet):
        self.spreadsheet=spreadsheet
        self.toolbar=QToolBar("Toolbar")
        self.toolbar.setMovable(False)
        self.toolbar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.toolbar.setIconSize(QSize(20,20))
        self.toolbar.setStyleSheet("QToolBar{spacing:6px;}")
        spreadsheet.addToolBar(self.toolbar)
        self.new_action=QAction("New File",spreadsheet)
        self.new_action.setIcon(self.get_icon("New File"))
        self.open_action=QAction("Open File",spreadsheet)
        self.open_action.setIcon(self.get_icon("Open File"))
        self.save_action=QAction("Save File",spreadsheet)
        self.save_action.setIcon(self.get_icon("Save File"))
        self.export_pdf_action=QAction("Export PDF",spreadsheet)
        self.export_pdf_action.setIcon(self.get_icon("Export PDF"))
        self.export_image_action=QAction("Export Image",spreadsheet)
        self.export_image_action.setIcon(self.get_icon("Export Image"))
        self.undo_action=QAction("Undo",spreadsheet)
        self.undo_action.setIcon(self.get_icon("Undo"))
        self.redo_action=QAction("Redo",spreadsheet)
        self.redo_action.setIcon(self.get_icon("Redo"))
        self.copy_action=QAction("Copy",spreadsheet)
        self.copy_action.setIcon(self.get_icon("Copy"))
        self.cut_action=QAction("Cut",spreadsheet)
        self.cut_action.setIcon(self.get_icon("Cut"))
        self.paste_action=QAction("Paste",spreadsheet)
        self.paste_action.setIcon(self.get_icon("Paste"))
        self.bold_action=QAction("Bold",spreadsheet)
        self.bold_action.setCheckable(True)
        self.bold_action.setIcon(self.get_icon("Bold"))
        self.italic_action=QAction("Italic",spreadsheet)
        self.italic_action.setCheckable(True)
        self.italic_action.setIcon(self.get_icon("Italic"))
        self.underline_action=QAction("Underline",spreadsheet)
        self.underline_action.setCheckable(True)
        self.underline_action.setIcon(self.get_icon("Underline"))
        self.strike_action=QAction("Strikethrough",spreadsheet)
        self.strike_action.setCheckable(True)
        self.strike_action.setIcon(self.get_icon("Strikethrough"))
        self.wrap_action=QAction("Wrap Text",spreadsheet)
        self.wrap_action.setCheckable(True)
        self.wrap_action.setIcon(self.get_icon("Wrap Text"))
        self.merge_action=QAction("Merge / Unmerge Cells",spreadsheet)
        self.merge_action.setIcon(self.get_icon("Merge Unmerge"))
        self.horizontal_alignment=QComboBox()
        self.horizontal_alignment.addItems(["Left","Center","Right"])
        self.vertical_alignment=QComboBox()
        self.vertical_alignment.addItems(["Top","Middle","Bottom"])
        self.font_color_action=QAction("Font Color",spreadsheet)
        self.font_color_action.setIcon(self.get_icon("Font Color"))
        self.fill_color_action=QAction("Fill Color",spreadsheet)
        self.fill_color_action.setIcon(self.get_icon("Fill Color"))
        self.border_button=QToolButton()
        self.border_button.setIcon(self.get_icon("Borders"))
        self.border_button.setIconSize(QSize(20,20))
        self.border_button.setFixedSize(32,32)
        self.border_button.setToolTip("Borders")
        self.border_button.setPopupMode(QToolButton.ToolButtonPopupMode.InstantPopup)
        self.border_menu=QMenu()
        self.border_button.setMenu(self.border_menu)
        self.all_border_action=self.border_menu.addAction("All Borders")
        self.outer_border_action=self.border_menu.addAction("Outer Borders")
        self.inner_border_action=self.border_menu.addAction("Inner Borders")
        self.top_border_action=self.border_menu.addAction("Top Border")
        self.bottom_border_action=self.border_menu.addAction("Bottom Border")
        self.left_border_action=self.border_menu.addAction("Left Border")
        self.right_border_action=self.border_menu.addAction("Right Border")
        self.no_border_action=self.border_menu.addAction("No Border")
        self.formula_button=QToolButton()
        self.formula_button.setIcon(self.get_icon("Formulas"))
        self.formula_button.setIconSize(QSize(20,20))
        self.formula_button.setFixedSize(40,40)
        self.formula_button.setToolTip("Formulas")
        self.formula_button.setPopupMode(QToolButton.ToolButtonPopupMode.InstantPopup)
        self.formula_menu=QMenu()
        self.formula_button.setMenu(self.formula_menu)
        self.sum_action=self.formula_menu.addAction("SUM")
        self.average_action=self.formula_menu.addAction("AVERAGE")
        self.count_action=self.formula_menu.addAction("COUNT")
        self.min_action=self.formula_menu.addAction("MIN")
        self.max_action=self.formula_menu.addAction("MAX")
        self.image_action=QAction("Insert Image",spreadsheet)
        self.image_action.setIcon(self.get_icon("Insert Image"))
        self.pdf_action=QAction("Insert PDF",spreadsheet)
        self.pdf_action.setIcon(self.get_icon("Insert PDF"))
        self.date_action=QAction("Insert Date",spreadsheet)
        self.date_action.setIcon(self.get_icon("Insert Date"))
        self.new_tab_action=QAction("New Tab",spreadsheet)
        self.new_tab_action.setIcon(self.get_icon("New Tab"))
        self.toolbar.addAction(self.new_action)
        self.toolbar.addAction(self.open_action)
        self.toolbar.addAction(self.save_action)
        self.toolbar.addAction(self.new_tab_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.export_pdf_action)
        self.toolbar.addAction(self.export_image_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.undo_action)
        self.toolbar.addAction(self.redo_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.copy_action)
        self.toolbar.addAction(self.cut_action)
        self.toolbar.addAction(self.paste_action)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.bold_action)
        self.toolbar.addAction(self.italic_action)
        self.toolbar.addAction(self.underline_action)
        self.toolbar.addAction(self.strike_action)
        self.toolbar.addAction(self.wrap_action)
        self.toolbar.addAction(self.merge_action)
        self.toolbar.addSeparator()
        self.toolbar.addWidget(self.horizontal_alignment)
        self.toolbar.addWidget(self.vertical_alignment)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.font_color_action)
        self.toolbar.addAction(self.fill_color_action)
        self.toolbar.addWidget(self.border_button)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.image_action)
        self.toolbar.addAction(self.pdf_action)
        self.toolbar.addAction(self.date_action)
        self.toolbar.addWidget(self.formula_button)
    
    def get_icon(self,name):
        icon_path=os.path.join(
            os.path.dirname(__file__),
            "icons",
            name+".png"
        )
        if os.path.exists(icon_path):
            return QIcon(icon_path)
        return QIcon()